### ISSUE TITLE
OPC RCW?

### ISSUE THREAD

**Issue by benfoster** [voyachek/ProcessControlStandards.OPC#1]
Hi,

Is your project designed to work with the OPC RCW library? I downloaded the source and while it compiles without issue the test project does not run so I wonder if I need to obtain the RCW dlls separately?

Thanks

**Comment by voyachek** [comment]
Hello,

I am glad your are interested in my project. It is my first GitHub experience. I uploaded some code, but it is not ready to use yet. I am planning to commit tested code at weekend. Project does not use OPC RCW library. the only dependency is OPC Core Components. Net Framework toolkit form OpcFoundation was bad support and contains some errors, which happened in communications with some OPC servers. I decided to publish simple and tiny OPC Client Toolkit on Github as an open source.

Best Regards, 
Vlad Voyachek.

From: Ben Foster 
Sent: Wednesday, February 12, 2014 12:55 PM
To: voyachek/ProcessControlStandards.OPC 
Subject: [ProcessControlStandards.OPC] OPC RCW? (#1)

Hi,

Is your project designed to work with the OPC RCW library? I downloaded the source and while it compiles without issue the test project does not run so I wonder if I need to obtain the RCW dlls separately?

Thanks

**Comment by benfoster** [comment]
Where can I obtain the OPC Core Components you refer to? I don't have access to any of the downloads on the OPC Foundation's sites since my company is not a member. Despite being an "open" standard, the OPC Foundation seem to be doing their best to keep control over it.

I look forward to seeing your changes.

**Comment by voyachek** [comment]
To download OPC Core components is not necessary to be a member. You must be registered on opcfoundation.org site. Registration is free for everyone.

Links:
http://www.opcfoundation.org/DownloadFile.aspx?CM=3&RI=821&CU=4
http://www.opcfoundation.org/DownloadFile.aspx?CM=3&RI=820&CU=4

**Comment by benfoster** [comment]
Thanks, I installed the Core Components and the example now works. I look forward to seeing the updates and if you need any help with testing let me know. I'm equally interested in creating a lightweight OPC client but unfortunately it's been a long time since I've done anything with COM. I was hoping to use the new OPC .NET client but this is only available to OPC Foundation (paying) members.
