### ISSUE TITLE
Two way binding on private property

### ISSUE THREAD

**Issue by benfoster** [voyachek/ProcessControlStandards.OPC#2]
The test application currently throws when right clicking a server node in the server browser. This is due to you having a two way binding set on `Command<T>.Name` which has a private setter.

Fix is to change:

```
<Setter Property="Header" Value="{Binding Name, Mode=TwoWay}"/>
```

to:

```
<Setter Property="Header" Value="{Binding Name}"/>
```

In MainWindow.xaml

Are you accepting pull-requests?

I'd love to chat to you more about this project. Having trawled through a number of OPC samples on the internet your library is by far the most comprehensive I've found.

Is there anything you need help with?

**Comment by voyachek** [comment]
Hello, thank you for interest. I have already resolved this bug. Yes I accept pull-requests.
